import Head from 'next/head';
import Image from 'next/image';
import Navbar from './shared/Navbar';
import Banner from './Home/Banner';
import logo from '../public/assets/logo.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="drawer drawer-mobile">
          <input id="dashboard-sidebar" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content">
            <Navbar />
            <Banner />

          </div>

          <div className="drawer-side">
            <label htmlFor="dashboard-sidebar" className="drawer-overlay"></label>
            <ul className="p-4 overflow-y-auto w-80 bg-accent text-base-content">
              <li className='flex justify-center items-center'>
                <Image
                  src={logo}
                  width={95}
                  height={95}
                  alt='' />
              </li>
            </ul>

          </div>
        </div>

      </div>
    </div>
  )
}
